application: naim
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  static_files: static/about.html
  upload: static/about.html

# BEGIN AUTO STATIC

- url: /about
  static_files: static/about.html
  upload: static/about.html

- url: /download
  static_files: static/download.html
  upload: static/download.html

- url: /icons/small/broken
  static_files: static/icons/small/broken.gif
  upload: static/icons/small/broken.gif

- url: /icons/small/goldstar
  static_files: static/icons/small/goldstar.png
  upload: static/icons/small/goldstar.png

- url: /icons/small/star_silver
  static_files: static/icons/small/star_silver.gif
  upload: static/icons/small/star_silver.gif

- url: /icons/sound1
  static_files: static/icons/sound1.gif
  upload: static/icons/sound1.gif

- url: /images/Sorcerer
  static_files: static/images/Sorcerer.png
  upload: static/images/Sorcerer.png

- url: /images/archlinux-logo
  static_files: static/images/archlinux-logo.png
  upload: static/images/archlinux-logo.png

- url: /images/background
  static_files: static/images/background.png
  upload: static/images/background.png

- url: /images/bebits-mainlogo
  static_files: static/images/bebits-mainlogo.gif
  upload: static/images/bebits-mainlogo.gif

- url: /images/debian
  static_files: static/images/debian.jpg
  upload: static/images/debian.jpg

- url: /images/freebsd-powerlogo
  static_files: static/images/freebsd-powerlogo.gif
  upload: static/images/freebsd-powerlogo.gif

- url: /images/freshmeat-logo
  static_files: static/images/freshmeat-logo.gif
  upload: static/images/freshmeat-logo.gif

- url: /images/gnu-head-sm
  static_files: static/images/gnu-head-sm.png
  upload: static/images/gnu-head-sm.png

- url: /images/header-fedora_logo01
  static_files: static/images/header-fedora_logo01.png
  upload: static/images/header-fedora_logo01.png

- url: /images/linuxorg
  static_files: static/images/linuxorg.gif
  upload: static/images/linuxorg.gif

- url: /images/naimlogo_nobubble_smaller
  static_files: static/images/naimlogo_nobubble_smaller.png
  upload: static/images/naimlogo_nobubble_smaller.png

- url: /images/netbsd
  static_files: static/images/netbsd.jpg
  upload: static/images/netbsd.jpg

- url: /images/nlogoeyes_small
  static_files: static/images/nlogoeyes_small.png
  upload: static/images/nlogoeyes_small.png

- url: /images/opendarwin-hexley-1
  static_files: static/images/opendarwin-hexley-1.png
  upload: static/images/opendarwin-hexley-1.png

- url: /images/smgl_logo
  static_files: static/images/smgl_logo.png
  upload: static/images/smgl_logo.png

- url: /images/sourcemage_banner
  static_files: static/images/sourcemage_banner.png
  upload: static/images/sourcemage_banner.png

- url: /images/tucows-logo
  static_files: static/images/tucows-logo.gif
  upload: static/images/tucows-logo.gif

- url: /lists
  static_files: static/lists.html
  upload: static/lists.html

- url: /packages
  static_files: static/packages.html
  upload: static/packages.html

- url: /quickstart
  static_files: static/quickstart.html
  upload: static/quickstart.html

- url: /screenimages/216.37.254.153/vince/stuff/naim
  static_files: static/screenimages/216.37.254.153/vince/stuff/naim.png
  upload: static/screenimages/216.37.254.153/vince/stuff/naim.png

- url: /screenimages/250/2003.07.26_shot1
  static_files: static/screenimages/250/2003.07.26_shot1.jpg
  upload: static/screenimages/250/2003.07.26_shot1.jpg

- url: /screenimages/250/achin-naim
  static_files: static/screenimages/250/achin-naim.jpg
  upload: static/screenimages/250/achin-naim.jpg

- url: /screenimages/250/aimisland-naimwindows
  static_files: static/screenimages/250/aimisland-naimwindows.png
  upload: static/screenimages/250/aimisland-naimwindows.png

- url: /screenimages/250/chad-naim-uptime
  static_files: static/screenimages/250/chad-naim-uptime.jpg
  upload: static/screenimages/250/chad-naim-uptime.jpg

- url: /screenimages/250/cleaner-naim
  static_files: static/screenimages/250/cleaner-naim.png
  upload: static/screenimages/250/cleaner-naim.png

- url: /screenimages/250/cory-naim
  static_files: static/screenimages/250/cory-naim.png
  upload: static/screenimages/250/cory-naim.png

- url: /screenimages/250/kassah-naim
  static_files: static/screenimages/250/kassah-naim.jpg
  upload: static/screenimages/250/kassah-naim.jpg

- url: /screenimages/250/naim1
  static_files: static/screenimages/250/naim1.png
  upload: static/screenimages/250/naim1.png

- url: /screenimages/250/naim2
  static_files: static/screenimages/250/naim2.png
  upload: static/screenimages/250/naim2.png

- url: /screenimages/250/naim3
  static_files: static/screenimages/250/naim3.png
  upload: static/screenimages/250/naim3.png

- url: /screenimages/250/naim4
  static_files: static/screenimages/250/naim4.png
  upload: static/screenimages/250/naim4.png

- url: /screenimages/250/naim5
  static_files: static/screenimages/250/naim5.png
  upload: static/screenimages/250/naim5.png

- url: /screenimages/250/naim6
  static_files: static/screenimages/250/naim6.png
  upload: static/screenimages/250/naim6.png

- url: /screenimages/250/studycisco-naim
  static_files: static/screenimages/250/studycisco-naim.png
  upload: static/screenimages/250/studycisco-naim.png

- url: /screenimages/250/vagabond-screenshot
  static_files: static/screenimages/250/vagabond-screenshot.png
  upload: static/screenimages/250/vagabond-screenshot.png

- url: /screenimages/250/vince-naim
  static_files: static/screenimages/250/vince-naim.png
  upload: static/screenimages/250/vince-naim.png

- url: /screenimages/250/vinceflash-snapshot3
  static_files: static/screenimages/250/vinceflash-snapshot3.jpg
  upload: static/screenimages/250/vinceflash-snapshot3.jpg

- url: /screenimages/250/vinceflash-usingnaim
  static_files: static/screenimages/250/vinceflash-usingnaim.jpg
  upload: static/screenimages/250/vinceflash-usingnaim.jpg

- url: /screenimages/aimisland.com/naimwindows
  static_files: static/screenimages/aimisland.com/naimwindows.gif
  upload: static/screenimages/aimisland.com/naimwindows.gif

- url: /screenimages/andrewchin.net/personal/naim3
  static_files: static/screenimages/andrewchin.net/personal/naim3.jpg
  upload: static/screenimages/andrewchin.net/personal/naim3.jpg

- url: /screenimages/andrewchin.net/tmp/inaim
  static_files: static/screenimages/andrewchin.net/tmp/inaim.jpg
  upload: static/screenimages/andrewchin.net/tmp/inaim.jpg

- url: /screenimages/chadp.net/chad/images/naim-uptime
  static_files: static/screenimages/chadp.net/chad/images/naim-uptime.jpg
  upload: static/screenimages/chadp.net/chad/images/naim-uptime.jpg

- url: /screenimages/derceto.net/cleaner/naim
  static_files: static/screenimages/derceto.net/cleaner/naim.png
  upload: static/screenimages/derceto.net/cleaner/naim.png

- url: /screenimages/eminence32.net/achin/naim
  static_files: static/screenimages/eminence32.net/achin/naim.jpg
  upload: static/screenimages/eminence32.net/achin/naim.jpg

- url: /screenimages/hobbes.unprompted.com/cory/naim
  static_files: static/screenimages/hobbes.unprompted.com/cory/naim.png
  upload: static/screenimages/hobbes.unprompted.com/cory/naim.png

- url: /screenimages/naim1
  static_files: static/screenimages/naim1.png
  upload: static/screenimages/naim1.png

- url: /screenimages/naim2
  static_files: static/screenimages/naim2.png
  upload: static/screenimages/naim2.png

- url: /screenimages/naim3
  static_files: static/screenimages/naim3.png
  upload: static/screenimages/naim3.png

- url: /screenimages/naim4
  static_files: static/screenimages/naim4.png
  upload: static/screenimages/naim4.png

- url: /screenimages/naim5
  static_files: static/screenimages/naim5.png
  upload: static/screenimages/naim5.png

- url: /screenimages/naim6
  static_files: static/screenimages/naim6.png
  upload: static/screenimages/naim6.png

- url: /screenimages/pqse-iphone
  static_files: static/screenimages/pqse-iphone.jpg
  upload: static/screenimages/pqse-iphone.jpg

- url: /screenimages/studycisco.sitesled.com/naim
  static_files: static/screenimages/studycisco.sitesled.com/naim.png
  upload: static/screenimages/studycisco.sitesled.com/naim.png

- url: /screenimages/tlp.lickwid.net/jornada/screenshots/j720naim1
  static_files: static/screenimages/tlp.lickwid.net/jornada/screenshots/j720naim1.jpg
  upload: static/screenimages/tlp.lickwid.net/jornada/screenshots/j720naim1.jpg

- url: /screenimages/vagabond.apocalyptic-high.org/screenshot
  static_files: static/screenimages/vagabond.apocalyptic-high.org/screenshot.png
  upload: static/screenimages/vagabond.apocalyptic-high.org/screenshot.png

- url: /screenimages/vinceflash.tripod.com/snapshot3
  static_files: static/screenimages/vinceflash.tripod.com/snapshot3.jpg
  upload: static/screenimages/vinceflash.tripod.com/snapshot3.jpg

- url: /screenimages/vinceflash.tripod.com/usingnaim
  static_files: static/screenimages/vinceflash.tripod.com/usingnaim.jpg
  upload: static/screenimages/vinceflash.tripod.com/usingnaim.jpg

- url: /screenimages/wbru.com/achin/naimshot
  static_files: static/screenimages/wbru.com/achin/naimshot.jpg
  upload: static/screenimages/wbru.com/achin/naimshot.jpg

- url: /screenimages/will.kassah.net/share/naim
  static_files: static/screenimages/will.kassah.net/share/naim.jpg
  upload: static/screenimages/will.kassah.net/share/naim.jpg

- url: /screenimages/www.cknoerle.gmxhome.de/2003.07.26_shot1
  static_files: static/screenimages/www.cknoerle.gmxhome.de/2003.07.26_shot1.jpg
  upload: static/screenimages/www.cknoerle.gmxhome.de/2003.07.26_shot1.jpg

- url: /screenimages/www.notebookreview.com/assets/29913
  static_files: static/screenimages/www.notebookreview.com/assets/29913.jpg
  upload: static/screenimages/www.notebookreview.com/assets/29913.jpg

- url: /screenshots
  static_files: static/screenshots.html
  upload: static/screenshots.html

# END AUTO STATIC
