application: space-bnb
version: 1
runtime: python27
api_version: 1
threadsafe: true
default_expiration: 0

handlers:
- url: /api/.*
  script: spacebnb.app

- url: /
  static_files: static/index.html
  upload: static/index.html

- url: /
  static_dir: static

inbound_services:
- warmup
