application: spacebnb
version: 1
runtime: python27
api_version: 1
threadsafe: true
default_expiration: 0

handlers:
- url: /api/.*
  script: spacebnb.app
  login: required

- url: /
  static_files: static/index.html
  upload: static/index.html
  login: required

- url: /
  static_dir: static
  login: required

inbound_services:
- warmup
