Vagrant.configure('2') do |config|

  config.vm.box = 'precise64'
  config.vm.box_url = 'http://files.vagrantup.com/precise64.box'

  config.vm.define 'dev', primary: true do |dev|
    dev.vm.hostname = 'spacex-dev'
    dev.vm.network :forwarded_port, :guest => 9090, :host => 9090
  end

  config.vm.provision :shell, :path => 'bootstrap.sh'
end
